apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: pod-demo
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: pod-demo
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  hostNetwork: true
  dnsPolicy: Default
